# Generated by Django 3.0.8 on 2020-07-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssignmentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='videofile',
            field=models.FileField(help_text='upload course vedio.', null=True, upload_to='course/videos'),
        ),
    ]
