# Generated by Django 3.0.8 on 2020-08-01 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssignmentApp', '0002_auto_20200731_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='videofile',
        ),
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.FileField(help_text='upload course vedio.', null=True, upload_to='course/images', verbose_name='Course Image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='Provide course description.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, help_text='Provide course title.', max_length=30, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='CourseVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vediofile', models.FileField(help_text='upload course vedio.', null=True, upload_to='course/videos', verbose_name='Vedio File')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssignmentApp.Course')),
            ],
            options={
                'verbose_name': 'Course Video',
                'verbose_name_plural': 'Course Videos',
            },
        ),
    ]
