# Generated by Django 3.0.8 on 2020-08-01 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssignmentApp', '0003_auto_20200801_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideos',
            name='Course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_videos', to='AssignmentApp.Course'),
        ),
    ]
